### PR TITLE
Bump version to 0.16.1

### PR DESCRIPTION
**Pull request by thewtex**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewtex** [comment]
@conda-forge-admin, please rerender

**Comment by thewtex** [comment]
```
  File "/home/conda/feedstock_root/build_artifacts/itkwidgets_1554607320241/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libX11.so.6: cannot open shared object file: No such file or directory
```

@mdboom @ocefpaf @tacaswell any hints on how to address this in the Docker build? It is related to the matplotlib import.

**Comment by ocefpaf** [comment]
> @mdboom @ocefpaf @tacaswell any hints on how to address this in the Docker build? It is relate to the matplotlib import.

You may have to add a you requirements file like this one:

https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/yum_requirements.txt

conda-forge's docker image no longer ships any X11/graphic stuff that is expected to be available on the user machine. We have to use the [CDTs](https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cdt#core-dependency-tree-packages-cdt) for linking at the build phase and add a you requirement file if you need the functionality at the test phase. See https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cdt#core-dependency-tree-packages-cdt

**Comment by thewtex** [comment]
@ocefpaf excellent, thank you for the explanation!

Let's try it...

**Comment by thewtex** [comment]
@conda-forge-admin, please rerender

**Comment by thewtex** [comment]
Worked! :+1:

**Pull request merged**
